spring.application.name=ConectaFamiliaBackend

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# MariaDB Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/conectafamilia_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/conectafamilia_mongo
