spring.application.name=ConectaFamiliaBackend

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# H2 Database Configuration (In-Memory)
spring.datasource.url=jdbc:h2:mem:conectafamilia_db;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use H2 dialect for the in-memory H2 database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/conectafamilia_mongo
